"""Add required tables

Revision ID: 000
Revises: 
Create Date: 2023-03-12 20:10:26.280037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '000'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('places',
        sa.Column('place_id', sa.Integer(), nullable=False),
        sa.Column('latitude', sa.Float(), nullable=False),
        sa.Column('longitude', sa.Float(), nullable=False),
        sa.Column('address', sa.String(length=512), nullable=True),
        sa.PrimaryKeyConstraint('place_id')
    )
    op.create_table('users',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=64), nullable=False),
        sa.Column('phone_number', sa.String(length=32), nullable=False),
        sa.Column('password', sa.String(length=256), nullable=False),
        sa.PrimaryKeyConstraint('user_id'),
        sa.UniqueConstraint('phone_number')
    )
    op.create_table('avatars',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('image', sa.LargeBinary(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
        sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('items',
        sa.Column('item_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=64), nullable=True),
        sa.Column('description', sa.String(length=1024), nullable=True),
        sa.Column('category', sa.Enum('phones', 'keys', 'documents', 'wallets', 'accessories', 'others', name='itemcategory'), nullable=True),
        sa.Column('author_id', sa.Integer(), nullable=False),
        sa.Column('return_way', sa.Enum('contact', 'left', 'other', name='itemreturn'), nullable=True),
        sa.Column('place_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], ),
        sa.ForeignKeyConstraint(['place_id'], ['places.place_id'], ),
        sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('item_images',
        sa.Column('image_id', sa.Integer(), nullable=False),
        sa.Column('item_id', sa.Integer(), nullable=False),
        sa.Column('image', sa.LargeBinary(), nullable=True),
        sa.Column('is_first', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
        sa.PrimaryKeyConstraint('image_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_images')
    op.drop_table('items')
    op.drop_table('avatars')
    op.drop_table('users')
    op.drop_table('places')
    # ### end Alembic commands ###
